import { AttendanceRecord } from '../types';

export const INITIAL_DEMO_RECORDS: AttendanceRecord[] = [
  // Today's entries
  {
    id: 'demo-1',
    name: 'Md. Tariqul Islam',
    designation: 'Branch Manager',
    date: '2026-07-30',
    timeStamp: '08:52:10',
    clockOutTime: '17:05:00',
    status: 'On Time',
    workHours: 8.2,
    notes: 'Regular check-in',
  },
  {
    id: 'demo-2',
    name: 'Kabir Hossain',
    designation: 'Accounts Officer',
    date: '2026-07-30',
    timeStamp: '08:58:34',
    clockOutTime: '17:15:00',
    status: 'On Time',
    workHours: 8.2,
  },
  {
    id: 'demo-3',
    name: 'Abu Raihan',
    designation: 'Store In-Charge',
    date: '2026-07-30',
    timeStamp: '09:05:12',
    clockOutTime: '17:00:00',
    status: 'On Time',
    workHours: 7.9,
  },
  {
    id: 'demo-4',
    name: 'Sabbir Ahmed',
    designation: 'Senior Sales Executive',
    date: '2026-07-30',
    timeStamp: '09:22:45',
    clockOutTime: '17:30:00',
    status: 'Late',
    workHours: 8.1,
    notes: 'Traffic delay on Daulatpur Highway',
  },
  {
    id: 'demo-5',
    name: 'Mostafizur Rahman',
    designation: 'Field Operations Officer',
    date: '2026-07-30',
    timeStamp: '08:45:00',
    clockOutTime: '16:45:00',
    status: 'On Time',
    workHours: 8.0,
  },
  {
    id: 'demo-6',
    name: 'Mehedi Hasan',
    designation: 'bKash Distribution Officer',
    date: '2026-07-30',
    timeStamp: '09:40:15',
    clockOutTime: '17:00:00',
    status: 'Late',
    workHours: 7.3,
  },
  {
    id: 'demo-7',
    name: 'Sharmin Akter',
    designation: 'Computer Operator',
    date: '2026-07-30',
    timeStamp: '08:55:20',
    clockOutTime: '17:00:00',
    status: 'On Time',
    workHours: 8.1,
  },
  {
    id: 'demo-8',
    name: 'Tanvir Hossain',
    designation: 'Delivery In-Charge',
    date: '2026-07-30',
    timeStamp: '09:02:00',
    clockOutTime: '16:30:00',
    status: 'Early Out',
    workHours: 7.5,
    notes: 'Field delivery visit to Bheramara',
  },

  // Yesterday's entries
  {
    id: 'demo-9',
    name: 'Md. Tariqul Islam',
    designation: 'Branch Manager',
    date: '2026-07-29',
    timeStamp: '08:48:12',
    clockOutTime: '17:20:00',
    status: 'On Time',
    workHours: 8.5,
  },
  {
    id: 'demo-10',
    name: 'Kabir Hossain',
    designation: 'Accounts Officer',
    date: '2026-07-29',
    timeStamp: '08:59:00',
    clockOutTime: '17:05:00',
    status: 'On Time',
    workHours: 8.1,
  },
  {
    id: 'demo-11',
    name: 'Abu Raihan',
    designation: 'Store In-Charge',
    date: '2026-07-29',
    timeStamp: '09:01:10',
    clockOutTime: '17:00:00',
    status: 'On Time',
    workHours: 8.0,
  },
  {
    id: 'demo-12',
    name: 'Sabbir Ahmed',
    designation: 'Senior Sales Executive',
    date: '2026-07-29',
    timeStamp: '08:50:30',
    clockOutTime: '17:10:00',
    status: 'On Time',
    workHours: 8.3,
  },
  {
    id: 'demo-13',
    name: 'Mostafizur Rahman',
    designation: 'Field Operations Officer',
    date: '2026-07-29',
    timeStamp: '09:28:10',
    clockOutTime: '17:00:00',
    status: 'Late',
    workHours: 7.5,
  },
  {
    id: 'demo-14',
    name: 'Mehedi Hasan',
    designation: 'bKash Distribution Officer',
    date: '2026-07-29',
    timeStamp: '08:54:00',
    clockOutTime: '17:00:00',
    status: 'On Time',
    workHours: 8.1,
  },
  {
    id: 'demo-15',
    name: 'Sharmin Akter',
    designation: 'Computer Operator',
    date: '2026-07-29',
    timeStamp: '08:57:40',
    clockOutTime: '17:00:00',
    status: 'On Time',
    workHours: 8.0,
  },

  // Earlier dates in the month
  {
    id: 'demo-16',
    name: 'Md. Tariqul Islam',
    designation: 'Branch Manager',
    date: '2026-07-28',
    timeStamp: '08:50:00',
    clockOutTime: '17:15:00',
    status: 'On Time',
    workHours: 8.4,
  },
  {
    id: 'demo-17',
    name: 'Kabir Hossain',
    designation: 'Accounts Officer',
    date: '2026-07-28',
    timeStamp: '09:18:22',
    clockOutTime: '17:00:00',
    status: 'Late',
    workHours: 7.7,
  },
  {
    id: 'demo-18',
    name: 'Sabbir Ahmed',
    designation: 'Senior Sales Executive',
    date: '2026-07-28',
    timeStamp: '08:55:00',
    clockOutTime: '17:05:00',
    status: 'On Time',
    workHours: 8.1,
  },
  {
    id: 'demo-19',
    name: 'Abu Raihan',
    designation: 'Store In-Charge',
    date: '2026-07-28',
    timeStamp: '08:58:00',
    clockOutTime: '17:00:00',
    status: 'On Time',
    workHours: 8.0,
  },
  {
    id: 'demo-20',
    name: 'Sharmin Akter',
    designation: 'Computer Operator',
    date: '2026-07-28',
    timeStamp: '08:52:15',
    clockOutTime: '17:00:00',
    status: 'On Time',
    workHours: 8.1,
  },
  {
    id: 'demo-21',
    name: 'Md. Tariqul Islam',
    designation: 'Branch Manager',
    date: '2026-07-27',
    timeStamp: '08:55:00',
    clockOutTime: '17:10:00',
    status: 'On Time',
    workHours: 8.25,
  },
  {
    id: 'demo-22',
    name: 'Kabir Hossain',
    designation: 'Accounts Officer',
    date: '2026-07-27',
    timeStamp: '08:50:00',
    clockOutTime: '17:00:00',
    status: 'On Time',
    workHours: 8.16,
  },
  {
    id: 'demo-23',
    name: 'Abu Raihan',
    designation: 'Store In-Charge',
    date: '2026-07-27',
    timeStamp: '09:25:00',
    clockOutTime: '17:00:00',
    status: 'Late',
    workHours: 7.58,
  }
];

export const DESIGNATIONS_LIST = [
  'All Designations',
  'Branch Manager',
  'Accounts Officer',
  'Store In-Charge',
  'Senior Sales Executive',
  'Field Operations Officer',
  'bKash Distribution Officer',
  'Computer Operator',
  'Delivery In-Charge'
];
